@startuml
    
  actor "Client"  
  box "Server Cluster" #99CCFF
  participant "Follower" as Follower
  participant "Leader" as Leader
  participant "OtherFollower" as OtherFollower
	end box
  activate Leader

  note Over Client 
    In questo schema, è espresso 
    il caso d'uso in cui un client 
    richiede una determinata modifica
    al cluster, in manieà semplificata
    per non esagerare con i blocchi alt.
    Inoltre nello schema,
    non si tengono in considerazione i
    classici failure della rete
  end note
  alt Indirect request
  Client ->> Follower : Send request 
  activate Follower
  Follower --> Client : return leader address
  Client ->> Leader : Send request

  deactivate Follower
  else Direct request
  Client ->> Leader : Send request
  end group

  loop Indefinite
    Leader ->> Follower : AppendEntries()
    activate Follower
    Leader ->> OtherFollower : AppendEntrie()
    activate OtherFollower
    Follower --> Leader : Ack and state
    OtherFollower --> Leader : Ack and state
    deactivate Follower
    deactivate OtherFollower
      opt if ackNum > sizeCluster/2-1
        Leader --> Client : return result
    end group
  end group
@enduml