/*
 * This Scala source file was generated by the Gradle 'init' task.
 */
package it.unibo.sd1920.akka_raft

class Library {
  def someLibraryMethod(): Boolean = true
}

object prova extends App {
  println("ciao")
}
