@startuml
  box "Server Cluster" #99CCFF 
    participant "Followers" as Followers
    participant "Candidate" as Candidate
    participant "New Leader" as Leader
    participant "Old Leader" as OldLeader

  activate Candidate
  
  Candidate ->> Followers : Send N vote request
  activate Followers
  Followers -->> Candidate : Receive back the votes
  deactivate Followers
  
  Candidate ->> Leader ** : <<become leader>>
  deactivate Candidate
  activate Leader
  deactivate Candidate
  Leader ->> OldLeader : AppendEntries()
  activate OldLeader
  OldLeader ->> Followers: <<become follower>>
  deactivate OldLeader

  loop Indefinite
    Leader -> Leader ++ : Start Timer
    return Timers Triggers
    Leader ->> Followers : AppendEntries()
    activate Followers
    Followers --> Leader : Ack and state
    deactivate Followers
  end group
end box
@enduml