@startuml
  box "Server Cluster" #99CCFF 
    participant "Followers" as Followers
    participant "Candidate" as Candidate
    participant "New Leader" as Leader
    participant "Old Leader" as OldLeader

  activate OldLeader
  activate Followers
  activate Candidate
  
  Candidate ->> Followers : Send N vote request
  Followers -->> Candidate : Receive back the votes
  
  Candidate ->> Leader ** : <<become leader>>
  activate Leader
  deactivate Candidate 
  Leader ->> OldLeader : AppendEntries()
  OldLeader ->> Followers: <<become follower>>
  deactivate OldLeader

  loop Indefinite
    Leader -> Leader ++ : Start Timer
    return Timers Triggers
    Leader ->> Followers : AppendEntries()
    Followers --> Leader : Ack and state
  end group
end box
@enduml