/*
 * This Scala Testsuite was generated by the Gradle 'init' task.
 */
package it.unibo.sd1920.akka_raft

import org.junit.runner.RunWith
import org.scalatest.FunSuite
import org.scalatest.junit.JUnitRunner

@RunWith(classOf[JUnitRunner])
class LibrarySuite extends FunSuite {
  test("SomeLibraryMethod is always true") {
    def library = new Library()
    assert(library.someLibraryMethod)
  }
}
